### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by ralfw** [Swyx/totalorder#6]
I think the homepage could be streamlined. There should be only 2 options:

* Create new backlog by entering a title and clicking a button. If the user is already logged in, the backlog will be created right away. If not, a login page is shown first (from which a registration can be started).
* Bring a backlog in order by entering a backlog id. If anonymous ordering is ok, the backlog is shown right away. If not and the user is not logged in yet, then a login page (plus registration) is shown first.

No option to check the current total order on the homepage. A backlog owner needs to login first and then choose from the list of backlogs. Or she received an email notification with a link to a specific backlog with an updated total order.

Ideally, I think, there should even be two "homepages": one for backlog owners (POs) and one for team members. Eg `talorder.io` for owners. It all starts with a backlog, doesn't it? And then maybe `arrange.totalorder.io` for members to bring issues into an order. (Of course both pages link to each other.)

On the backlog page a link is presented to copy to the clipboard and then be handed out to members, e.g. `arrange,totalorder.io/LTH392`.

I'm drawing this view from how it's done here: https://www.mentimeter.com - a tool to engage the audience of a presentation. Under this URL you design your queries. But to answer the query the audience has to go to "http://www.menti.com" and enter a code. This proved to be very easy for everybody.

**Comment by martinh2011** [comment]
I like the idea and totalorder.io as a domain. However, that domain costs 99€ per year. But I just reserved totalorder.de (privatelyj which is only 9€ in the first year.

Consider it a donation to the project 🙂
